/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MayorRole;

import Business.CrimeSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PoliceEnterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MeetingRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lakshmi
 */
public class ArrangeMeetingJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private CrimeSystem system;
    /**
     * Creates new form ArrangeMeetingJPanel
     */
    public ArrangeMeetingJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, CrimeSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.system = system;
        populatePoliceOfficerCombo();
    }
    
    private void populatePoliceOfficerCombo(){
        for(Network n: system.getNetworkList()){
            for(Enterprise e:n.getEnterpriseDirectory().getEnterpriseList()){
                for(UserAccount u: e.getUserAccountDirectory().getUserAccountList()){
                    comboPoliceOfficer.addItem(u);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAgenda = new javax.swing.JTextField();
        txtMeetingVenue = new javax.swing.JTextField();
        jMeetingDate = new com.toedter.calendar.JDateChooser();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboPoliceOfficer = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel1.setText("Arrange Meeting");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 58, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel2.setText("Meeting Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel3.setText("Meeting venue");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel4.setText("Agenda");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));
        add(txtAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 234, 100, -1));
        add(txtMeetingVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 196, 100, -1));
        add(jMeetingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 158, 100, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel5.setText("Message");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 265, 100, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel6.setText("Select Senior Police Officer");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 129, -1, -1));

        comboPoliceOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPoliceOfficerActionPerformed(evt);
            }
        });
        add(comboPoliceOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 125, 146, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        UserAccount userAccount = (UserAccount)comboPoliceOfficer.getSelectedItem();
        jMeetingDate.setDateFormatString("dd/MM/yyyy");
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        String meetingDate = sdf.format(jMeetingDate.getDate());
        String venue = txtMeetingVenue.getText();
        String agenda = txtAgenda.getText();
        String message = txtMessage.getText();
        
        MeetingRequest request = new MeetingRequest();
        request.setAgenda(agenda);        
        request.setSender(account);
        request.setReceiver(userAccount);
        request.setMeetingDate(meetingDate);
        request.setMeetingVenue(venue);
        request.setMessage(message);

        request.setStatus("Sent");

        Enterprise enterprise = null;
        for(Network n: system.getNetworkList()){
            for (Enterprise enterprise1 : n.getEnterpriseDirectory().getEnterpriseList()){
                if (enterprise1 instanceof PoliceEnterprise){
                    enterprise = enterprise1;
                    break;
                }
            }
        }
        if (enterprise!=null){
            System.out.println("inside enterprise"+enterprise);
            enterprise.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(this, "Request Placed Successfully!!!!", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void comboPoliceOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPoliceOfficerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPoliceOfficerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageMeetingsJPanel dwjp = (ManageMeetingsJPanel) component;
        dwjp.populateMeetingTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comboPoliceOfficer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.toedter.calendar.JDateChooser jMeetingDate;
    private javax.swing.JTextField txtAgenda;
    private javax.swing.JTextField txtMeetingVenue;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
