/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CareGiverRole;

import Business.Caregiver.Caregiver;
import Business.Caregiver.CaregiverDirectory;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import Business.Vitalsign.Vitalsign;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Lakshmi
 */
public class ManageHouseholdJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private CaregiverDirectory careGiverDirectory;
    /**
     * Creates new form ManageHouseholdJPanel
     */
    public ManageHouseholdJPanel(JPanel userProcessContainer, UserAccount userAccount, CaregiverDirectory careGiverDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.careGiverDirectory = careGiverDirectory;
        populateTable();
    }
    
    private void populateTable(){
        Person person = null;
        for(Caregiver c: careGiverDirectory.getCareGiverList()){
            if(c.getCareGiverfirstName().equals(userAccount.getEmployee().getName())){
                person = c.getPerson();
                DefaultTableModel model = (DefaultTableModel) viewVitalSignsJTable.getModel();
                model.setRowCount(0);
                if (person != null) {
                    int age = person.getAge();

                    if (person.getVitalSignHistory().getVitalSignList().isEmpty()) {
                        JOptionPane.showMessageDialog(this, "No vital signs found. Please add vital signs", "Error", JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }
                    for (Vitalsign vitalSign : person.getVitalSignHistory().getVitalSignList()) {
                        Object[] row = new Object[5];
                        row[0] = vitalSign;
                        row[1] = vitalSign.getBloodPressure();
                        row[2] = vitalSign.getHeartRate();
                        row[3] = vitalSign.getRespiratoryRate();
                        row[4] = person.getVitalSignHistory().VitalSignStatus(age, vitalSign);
                        model.addRow(row);
                    }
                }
            }
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewVitalSignsJTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel1.setText("Manage Person");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        viewVitalSignsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Timestamp", "Blood Pressure", "Heart Rate", "Respiratory Rate", "Status"
            }
        ));
        jScrollPane1.setViewportView(viewVitalSignsJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 140));

        btnBack.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable viewVitalSignsJTable;
    // End of variables declaration//GEN-END:variables
}
