/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.VictimRole;

import Business.CrimeSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PoliceEnterprise;
import Business.Household.Household;
import Business.Network.Network;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.Household;
import Business.Organization.PoliceOrganization;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CrimeWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Lakshmi
 */
public class RequestCrimeJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private CrimeSystem system;
    private PersonDirectory personDirectory;
    /**
     * Creates new form RequestCrimeJPanel
     */
    public RequestCrimeJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, CrimeSystem system, PersonDirectory personDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        this.personDirectory = personDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCrimeLocation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboCrimeType = new javax.swing.JComboBox();
        dateChooserCrimeOccured = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtCrimeReportedAt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        requestTestJButton1.setText("Send Request");
        requestTestJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButton1ActionPerformed(evt);
            }
        });
        add(requestTestJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel1.setText("Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 90, -1));

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel2.setText("Crime Type");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel3.setText("Crime Location");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));
        add(txtCrimeLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 89, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel4.setText("Crime Occured");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        comboCrimeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KIDNAPPING", "SEXUAL ASSAULT", "ACCIDENT", "CHILD ABUSE", "BURGLARY", "FORGERY", "MURDER", " " }));
        comboCrimeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCrimeTypeActionPerformed(evt);
            }
        });
        add(comboCrimeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 89, 30));
        add(dateChooserCrimeOccured, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel5.setText("Crime Reported At");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));
        add(txtCrimeReportedAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 90, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel6.setText("Request Crime");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButton1ActionPerformed
        try{
            if (checkEmptyInput())
            {
                String message = messageJTextField.getText();
                dateChooserCrimeOccured.setDateFormatString("dd/MM/yyyy");
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
                String d = sdf.format(dateChooserCrimeOccured.getDate());

                CrimeWorkRequest request = new CrimeWorkRequest();
                request.setMessage(message);
                request.setCrimeLocation(txtCrimeLocation.getText());
                txtCrimeReportedAt.setText(sdf.toString());
                request.setCrimeOccuredAt(d);
                String crimeType = (String)comboCrimeType.getSelectedItem();
                request.setCrimeType(crimeType);
                request.setSender(userAccount);
                request.setStatus("Sent");
                for(Person p: personDirectory.getPersonList()){
                    if(p.getFirstName().equals(userAccount.getEmployee().getName())){
                        request.setReceiver(p.getPoliceOfficer());
                    }
                }

                Organization org = null;
                for (Network n: system.getNetworkList()){
                    for(Enterprise e:n.getEnterpriseDirectory().getEnterpriseList()){
                        if(e instanceof PoliceEnterprise){
                            for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
                                if (organization instanceof PoliceOrganization){
                                    org = organization;
                                    break;
                                }
                            }
                        }
                    }
                }

                if (org!=null){
                    org.getWorkQueue().getWorkRequestList().add(request);
                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                }
                JOptionPane.showMessageDialog(this, "Request sent successfully!!", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Please enter all values", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please enter correct values", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_requestTestJButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ReportCrimeJPanel dwjp = (ReportCrimeJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboCrimeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCrimeTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCrimeTypeActionPerformed
    
    private Boolean checkEmptyInput()
    {
        if(txtCrimeLocation.getText().length()==0
            ||messageJTextField.getText().length()==0)
            {
                return false;
            }
            else{
                return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboCrimeType;
    private com.toedter.calendar.JDateChooser dateChooserCrimeOccured;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JButton requestTestJButton1;
    private javax.swing.JTextField txtCrimeLocation;
    private javax.swing.JTextField txtCrimeReportedAt;
    // End of variables declaration//GEN-END:variables
}
