/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.VictimRole;

import Business.CrimeSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.HouseholdOrganization;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.PageAttributes;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Lakshmi
 */
public class VictimWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private CrimeSystem system;
    
    
    /**
     * Creates new form VictimWorkAreaJPanel
     */
    public VictimWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,CrimeSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        System.out.println("victim area"+userAccount);
        lbluserName.setText(userAccount.getUsername());
        displayProfilePicture();
    }

    private void displayProfilePicture(){
        String filename=null;
        for(Person p: organization.getPersonDirectory().getPersonList()){
            if(p.getFirstName().equals(userAccount.getEmployee().getName())){
               filename = p.getProfilePic();
            }  
        } 
        
        ImageIcon icon=new ImageIcon(filename);
        lblProfilePic.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnProfileInformation = new javax.swing.JButton();
        btnCaregiver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbluserName = new javax.swing.JLabel();
        lblProfilePic = new javax.swing.JLabel();
        sensorInput = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel2.setText("Welcome ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel3.setText("My Work Area");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        btnProfileInformation.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnProfileInformation.setText("Profile Information");
        btnProfileInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileInformationActionPerformed(evt);
            }
        });
        add(btnProfileInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 252, -1));

        btnCaregiver.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnCaregiver.setText("Caregiver Information");
        btnCaregiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaregiverActionPerformed(evt);
            }
        });
        add(btnCaregiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 252, -1));

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jButton1.setText("Report Crime");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 252, -1));

        lbluserName.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        lbluserName.setText("jLabel4");
        add(lbluserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));
        add(lblProfilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 210, 90));

        sensorInput.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        sensorInput.setText("Sensor Input");
        sensorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sensorInputActionPerformed(evt);
            }
        });
        add(sensorInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 250, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileInformationActionPerformed
        // TODO add your handling code here:
        ProfileInformationJPanel profileInformationJPanel = new ProfileInformationJPanel(userProcessContainer, userAccount, organization.getPersonDirectory());
        userProcessContainer.add("profileInformationJPanel", profileInformationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProfileInformationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ReportCrimeJPanel profileInformationJPanel = new ReportCrimeJPanel(userProcessContainer, userAccount, organization, enterprise, system, organization.getPersonDirectory());
        userProcessContainer.add("profileInformationJPanel", profileInformationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCaregiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaregiverActionPerformed
        // TODO add your handling code here:
        CareGiverInformationJPanel careGiverJPanel = new CareGiverInformationJPanel(userProcessContainer, userAccount,enterprise, organization.getPersonDirectory());
        userProcessContainer.add("careGiverJPanel", careGiverJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCaregiverActionPerformed

    private void sensorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sensorInputActionPerformed
        // TODO add your handling code here:
        SensorInputJPanel sensorJPanel = new SensorInputJPanel(userProcessContainer, userAccount,enterprise, organization.getPersonDirectory());
        userProcessContainer.add("sensorJPanel", sensorJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_sensorInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaregiver;
    private javax.swing.JButton btnProfileInformation;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JLabel lbluserName;
    private javax.swing.JButton sensorInput;
    // End of variables declaration//GEN-END:variables
}
