/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.VictimRole;

import Business.CrimeSystem;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Lakshmi
 */
public class WorkActivityJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    private UserAccount account;
    private PersonDirectory personDirectory;
    /**
     * Creates new form WorkActivityJPanel
     */
    public WorkActivityJPanel(JPanel userProcessContainer, UserAccount account, PersonDirectory personDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.personDirectory = personDirectory;
    }
    
    private void saveValues(){
       for(Person p: personDirectory.getPersonList()){
            if(p.getFirstName().equals(account.getEmployee().getName())){
                p.setWorkLocation(String.valueOf(comboWorkLocation.getSelectedItem()));
                p.setBloodGroup(String.valueOf(comboBloodGroup.getSelectedItem()));
                p.setMorningTime(String.valueOf(comboMorning.getSelectedItem()));
                p.setEveningTime(String.valueOf(comboEvening.getSelectedItem()));
                p.setModeOfTransport(String.valueOf(comboTransport.getSelectedItem()));
            }  
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboMorning = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboEvening = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        comboWorkLocation = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        comboBloodGroup = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        comboTransport = new javax.swing.JComboBox();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Profile Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel3.setText("Work Location");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel4.setText("Work timings");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        comboMorning.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        comboMorning.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        add(comboMorning, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel5.setText("AM");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel6.setText("to");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        comboEvening.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        comboEvening.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        add(comboEvening, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel7.setText("PM");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, -1));

        comboWorkLocation.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        comboWorkLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Allston", "Back Bay", "Bay Village", "Beacon Hill", "Brighton", "Charlestown", "Chinatown/Leather District", "Dorchester", "Downtown", "East Boston", "Fenway Kenmore", "Hyde Park", "Jamaica Plain", "Mattapan", "Mid Dorchester", "Mission Hill", "North End", "Roslindale", "Roxbury", "South Boston", "South End", "West End", "West Roxbury" }));
        comboWorkLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboWorkLocationActionPerformed(evt);
            }
        });
        add(comboWorkLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 170, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel8.setText("Blood Group");
        jLabel8.setToolTipText("");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        comboBloodGroup.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        comboBloodGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        add(comboBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 157, -1));

        btnSave.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        btnBack.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jButton1.setText(">> Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel9.setText("Mode of Transport");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        comboTransport.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        comboTransport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Walking", "Driving", "Bicycling", "Subway/Bus/Commuter Rail", "Amtrack/Coach Buses", "Taxi" }));
        add(comboTransport, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        saveValues();
        UploadPhotoJPanel uploadPhotoJPanel = new UploadPhotoJPanel(userProcessContainer, account, personDirectory);
        userProcessContainer.add("uploadPhotoJPanel", uploadPhotoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboWorkLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboWorkLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboWorkLocationActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        saveValues();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox comboBloodGroup;
    private javax.swing.JComboBox comboEvening;
    private javax.swing.JComboBox comboMorning;
    private javax.swing.JComboBox comboTransport;
    private javax.swing.JComboBox comboWorkLocation;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
