/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PoliceOfficerRole;

import Business.CrimeSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PoliceOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Lakshmi
 */
public class ManagePoliceStationJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private CrimeSystem system;
    private Enterprise enterprise;
    private Organization organization;
    /**
     * Creates new form ManagePoliceStationJPanel
     */
    public ManagePoliceStationJPanel(JPanel userProcessContainer, Enterprise enterprise,UserAccount userAccount, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.organization = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCrimeReportList = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Police Station Activity");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 70, -1, -1));

        btnCrimeReportList.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnCrimeReportList.setText("Crime Report List");
        btnCrimeReportList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrimeReportListActionPerformed(evt);
            }
        });
        add(btnCrimeReportList, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 159, 205, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrimeReportListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrimeReportListActionPerformed
        // TODO add your handling code here:
        CrimeReportListJPanel crimeReportJPanel = new CrimeReportListJPanel(userProcessContainer, enterprise, userAccount, organization);
        userProcessContainer.add("crimeReportJPanel", crimeReportJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCrimeReportListActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCrimeReportList;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
