/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PoliceOfficerRole;

import Business.CrimeSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Lakshmi
 */
public class PoliceOfficerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount account;
    private CrimeSystem system;
    private Organization organization;
    
    /**
     * Creates new form PoliceOfficerWorkAreaJPanel
     */
    public PoliceOfficerWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, Organization organization, CrimeSystem system ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.organization = organization;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManagePoliceStation = new javax.swing.JButton();
        btnAnalytics = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Police Officer Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 204, -1));

        btnManagePoliceStation.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnManagePoliceStation.setText("Manage Police Station Activity");
        btnManagePoliceStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePoliceStationActionPerformed(evt);
            }
        });
        add(btnManagePoliceStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, 40));

        btnAnalytics.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        btnAnalytics.setText("Analytics");
        btnAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsActionPerformed(evt);
            }
        });
        add(btnAnalytics, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 270, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagePoliceStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePoliceStationActionPerformed
        // TODO add your handling code here:
        ManagePoliceStationJPanel managePoliceJPanel = new ManagePoliceStationJPanel(userProcessContainer, enterprise, account, organization);
        userProcessContainer.add("managePoliceJPanel", managePoliceJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePoliceStationActionPerformed

    private void btnAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsActionPerformed
        // TODO add your handling code here:
        AnalyticsJPanel analytics = new AnalyticsJPanel(userProcessContainer, enterprise, organization, system);
        userProcessContainer.add("analytics", analytics);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnalyticsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalytics;
    private javax.swing.JButton btnManagePoliceStation;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
